EDIT | husky

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -12,8 +12,8 @@ if [ "$branch" = "develop" ]; then
   exit 0
 fi
 
-if ! grep -qE "$commitRegex" "$branch"; then
-  echo "You can't commit directly to master branch, $branch"
-  exit 1
-fi
+#if ! grep -qE "$commitRegex" "$branch"; then
+#  echo "You can't commit directly to master branch, $branch"
+#  exit 1
+#fi
 
